Implement enroll method and interface
CSC207-2023Y-UofT/course-project-course-match-daddy pull request #60
Opened 2023-07-13 23:36 UTC by realdevvora

2023-07-18 02:57 UTC, uyoyo0 commented on app/src/main/java/com/example/coursematchdaddy/clean_architecture_layers/entities/interfaces/course_class_imports_implementations/ArtsAndSciencesCourseInterface.java
> +    public boolean enroll(User user);
Update the design doc to reflect the fact that you've added this method to the interface

2023-07-18 02:58 UTC, uyoyo0 commented on app/src/main/java/com/example/coursematchdaddy/clean_architecture_layers/entities/classes/course_subclasses/ArtsAndSciencesCourse.java
>  public class ArtsAndSciencesCourse extends Course {
Looks good

2023-07-18 02:58 UTC, uyoyo0 submitted a review, later dismissed

2023-07-19 02:21 UTC, JaspreetKhela requested changes
Please add comments to your code; you added some but try to add comments to the method signatures as well. Everything else looks good.

2023-07-20 14:16 UTC, GagandeepLubana approved these changes

2023-07-22 05:04 UTC, JaspreetKhela approved these changes

2023-07-22 05:49 UTC, uyoyo0 approved these changes
Looks even better with the comments

2023-07-22 14:21 UTC, GagandeepLubana approved these changes

2023-07-22 17:14 UTC, merged