14 feature 14 create usersurveydatainterface entity layer and survey class related interface
CSC207-2023Y-UofT/course-project-course-match-daddy pull request #63
Opened 2023-07-17 18:43 UTC by GagandeepLubana

2023-07-19 00:29 UTC, realdevvora commented on app/src/main/java/com/example/coursematchdaddy/clean_architecture_layers/entities/classes/Survey.java
just make sure to add these methods onto the CRC document, and its good

2023-07-19 00:30 UTC, realdevvora approved these changes
👍

2023-07-19 02:22 UTC, JaspreetKhela requested changes
Please add comments to your code. Everything else looks good.

2023-07-22 05:04 UTC, JaspreetKhela approved these changes

2023-07-22 05:52 UTC, uyoyo0 approved these changes
Looks good

2023-07-22 13:47 UTC, realdevvora approved these changes

2023-07-22 13:48 UTC, merged