38 feature 38 create viewprogramsrecommendationsinterface use case layer and recommendationalgorithm class related interface
CSC207-2023Y-UofT/course-project-course-match-daddy pull request #65
Opened 2023-07-18 01:36 UTC by uyoyo0

2023-07-19 00:35 UTC, realdevvora commented on app/src/main/java/com/example/coursematchdaddy/clean_architecture_layers/presenters/classes/LoginPresenter.java
considering that these are blank methods, I'm assuming you are going to change them later right?

2023-07-19 00:36 UTC, realdevvora commented on app/src/main/java/com/example/coursematchdaddy/clean_architecture_layers/presenters/classes/LoginPresenter.java
also be sure to add the changeView() method onto the doc

2023-07-19 02:23 UTC, JaspreetKhela requested changes
Please add comments to your code. Everything else looks good.

2023-07-20 13:40 UTC, GagandeepLubana approved these changes
LGTM

2023-07-20 19:22 UTC, LVaishno reviewed
The code makes sense and the comments look good

2023-07-20 23:38 UTC, LVaishno submitted a review, later dismissed
Approved

2023-07-22 05:06 UTC, JaspreetKhela approved these changes

2023-07-22 13:50 UTC, realdevvora approved these changes

2023-07-22 15:49 UTC, GagandeepLubana approved these changes

2023-07-22 17:15 UTC, merged