22 feature 22 create verifylogindatainterface use case layer and login class related interface
CSC207-2023Y-UofT/course-project-course-match-daddy pull request #66
Opened 2023-07-18 05:36 UTC by uyoyo0

Some notes:
`DBUsersGateway ` implements `VerifyLoginDataInterface` and I have only written methods that `DBUsersGateway `  must implement from  `VerifyLoginDataInterface`. This means that DBUsersGateway still has several unimplemented methods! 

My implementation also makes several assumptions regarding the implementation of some of the unimplemented methods so be sure to take a look at the comments I left within the file to make sure that we're all on the same page.

I already pushed the `VerifyLoginDataInterface` to a previous branch which is why its not here (32-feature-32-create-collectlogindatainterface-use-case-layer-and-login-class-related-interface. Should have pushed it here though, my bad)

2023-07-19 02:24 UTC, JaspreetKhela requested changes
Please add comments to your code. Everything else looks good.

2023-07-22 05:08 UTC, JaspreetKhela approved these changes

2023-07-22 13:51 UTC, realdevvora approved these changes

2023-07-23 02:10 UTC, realdevvora submitted a review, later dismissed

2023-07-23 02:27 UTC, M4N4VS1NGH approved these changes

2023-07-24 19:06 UTC, JaspreetKhela approved these changes

2023-07-24 22:25 UTC, M4N4VS1NGH approved these changes

2023-07-25 01:34 UTC, realdevvora approved these changes

2023-07-25 01:34 UTC, merged